name: gocf

on:
  schedule:
    - cron: '50 2 * * *'

jobs:
  gocf:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - name: Setup
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt install -yq golang pigz bzip2
      - name: Clone
        run: |
          git clone https://github.com/cloudflare/go
          sudo mv go /opt/
      - name: Make
        run: |
          cd /opt/go/src
          env CGO_ENABLED=0 ./make.bash
      - name: Tarball
        run: |
          cd /opt/go/bin
          cd /opt
          tar -cf /tmp/gocf.linux-amd64.tar go
          pigz -9 /tmp/gocf.linux-amd64.tar
      - name: Release
        run: |
          curl -L https://github.com/github-release/github-release/releases/download/v0.10.0/linux-amd64-github-release.bz2 | bzip2 -d >github-release
          chmod +x github-release
          ./github-release upload --replace --user phuslu --repo go --tag v0.0.0 --name gocf.linux-amd64.tar.gz --file /tmp/gocf.linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
